version: '3.8'

services:
  users:
    build:
      context: ./apps/users
    ports:
      - "4001:4001"

  products:
    build:
      context: ./apps/products
    ports:
      - "4002:4002"

  gateway:
    build:
      context: ./apps/gateway
    ports:
      - "4000:4000"
    depends_on:
      - users
      - products

